greeting:
  message: "hello"
  name: "quarkus"
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/confluent
      driver: org.postgresql.Driver
    username: postgres
    password: postgres
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
