greeting:
  message: "hello"
  name: "quarkus"
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test
      driver: org.h2.Driver
    username: sa
    password:
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    sql-load-script: import.sql
